version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: userpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-puserpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

  seeder:
    build:
      context: ./app
      dockerfile: dockerfile
    environment:
      DATABASE_URL: mysql://user:userpassword@mysql:3306/mydb
    command: sh -c "npx prisma db push --accept-data-loss && npx prisma db seed"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  app:
    build:
      context: ./app
      dockerfile: dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://user:userpassword@mysql:3306/mydb
    command: npm run dev
    depends_on:
      mysql:
        condition: service_healthy
      seeder:
        condition: service_completed_successfully

volumes:
  mysql_data: