// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from '@prisma/config';

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ใส่ URL ตรงนี้แทน หรือดึงจาก process.env
    url: process.env.DATABASE_URL || "mysql://user:userpassword@localhost:3306/mydb",
  },
});
