import './globals.css';
import React from 'react';

export const metadata = {
  title: 'An Astrology Web',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body>{children}</body>
    </html>
  );
}